# Generated by Django 5.0.6 on 2024-09-08 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminPannel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('roll_number', models.IntegerField(primary_key=True, serialize=False)),
                ('_class', models.CharField(max_length=20)),
                ('semester', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_number', models.IntegerField()),
                ('unit_title', models.CharField(blank=True, max_length=50)),
                ('className', models.CharField(max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('questions', models.TextField()),
                ('submit_by', models.CharField(blank=True, max_length=20)),
                ('unit_number', models.IntegerField(blank=True, null=True)),
                ('subject_name', models.CharField(blank=True, max_length=50)),
                ('semester', models.IntegerField(null=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='adminPannel.admin_registration')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_file', models.FileField(upload_to='assignment_File/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=10)),
                ('assignmentid', models.IntegerField(null=True)),
                ('massage', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments_manager.userdetails')),
            ],
        ),
    ]
