# Generated by Django 5.0.6 on 2024-09-08 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='student_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollnumber', models.IntegerField(null=True, unique=True)),
                ('enrollment', models.IntegerField(null=True, unique=True)),
                ('course', models.CharField(max_length=20, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('semester', models.IntegerField(null=True)),
                ('bio', models.TextField(max_length=255, null=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('address', models.TextField(blank=True, null=True)),
                ('profession', models.CharField(max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
